# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-20.04
    name: Build

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: npm -v

      # Check Docker in env
      - name: Checking Docker
        run: docker

      - name: Install node modules
        run: npm i

      - name: Build
        run: npm run build

      - name: Check files
        run: ls

#      - uses: actions/upload-artifact@v2
#        with:
#          name: my-artifact
#          path: dist

      # Build project in docker
      - name: Build in Docker
        run: |
          mkdir temp_build,
          cp src webextension-polyfill dockerile.Docker package.json package-lock.json tsconfig.json webpack.config.js temp_build,
          cd temp_build,
          echo checking current folder
          ls

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
